name: Code build

on:
  push:
    paths:
      - 'src/**'
      - '!.github/**'
      - '!*.md'
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        goarch: [386, amd64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd src
        GOARCH=${{ matrix.goarch }} go build

    - name: Test
      run: |
        cd src
        go test
