name: MacOS release

on:
  push:
    paths:
      - 'src/**'
      - '!.github/**'
      - '!*.md'      
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        goarch: [amd64,arm64]
    outputs:
      upload_url: ${{ steps.get_release.outputs.result }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Create binary and copy config file
        run: |
          mkdir -p ./${{ runner.os }}-${{ matrix.goarch }}
          cd src
          GOARCH=${{ matrix.goarch }} go build -o ./${{ runner.os }}-${{ matrix.goarch }}/bing-wp-download
          cp config.example ./${{ runner.os }}-${{ matrix.goarch }}/bing.conf.example
  
      - name: Create zip file
        run: zip -r ./src/${{ runner.os }}-${{ matrix.goarch }}/bing-wp-download-${{ runner.os }}-${{ matrix.goarch }}.zip ./src/${{ runner.os }}-${{ matrix.goarch }}/*
          
      - name: Create binary and copy config file
        run: |
          mkdir -p ./${{ runner.os }}-${{ matrix.goarch }}
          cd src
          GOARCH=${{ matrix.goarch }} go build -o ./${{ runner.os }}-${{ matrix.goarch }}/bing-wp-download
          cp config.example ./${{ runner.os }}-${{ matrix.goarch }}/bing.conf.example

      - name: Create zip file
        run: zip -r ./src/${{ runner.os }}-${{ matrix.goarch }}/bing-wp-download-${{ runner.os }}-${{ matrix.goarch }}.zip ./src/${{ runner.os }}-${{ matrix.goarch }}/*

      - name: Get Release
        id: get_release
        uses: actions/github-script@v5
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', '')
            });
            return release.data.upload_url;
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.result }}
          asset_path: ./src/${{ runner.os }}-${{ matrix.goarch }}/bing-wp-download-${{ runner.os }}-${{ matrix.goarch }}.zip
          asset_name: bing-wp-download-${{ runner.os }}-${{ matrix.goarch }}.zip
          asset_content_type: application/zip
    permissions:
      contents: write